spring:
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        open-in-view: false
    mvc:
        hiddenmethod:
            filter:
                enabled: true
